### ISSUE TITLE
Cum construiesc baza de date?

### ISSUE THREAD

**Issue by gabyadrian18** [Rillb3/busappschedule#1]
Salut!
Mi-ai putea arata cum sa construiesc baza de date în Firebase? 
(sau să-i faci un export la a ta ar fi de mult ajutor)
Mulțumesc!

**Comment by R8bert** [comment]
Salut, nu pot sa te ajut in detaliu dar pot sa iti arat cum arata baza de
date
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
cam asta este baza de date, bafta!

**Comment by gabyadrian18** [comment]
Salut, nu vad imaginile, poti sa le incarci undeva sau sa le trimiti la adresa de email gabiadrian02@gmail.com?

Multumesc frumos!

**Comment by R8bert** [comment]
am dar forward, incearca acum

**Comment by gabyadrian18** [comment]
Multumesc frumos, merge!

**Comment by R8bert** [comment]
Spor!
